# Generated by Django 3.1.6 on 2021-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='NOM_ENFANT', max_length=50)),
                ('prenom', models.CharField(db_column='PRENOM_ENFANT', max_length=50)),
            ],
        ),
    ]
